CREATE TABLE IF NOT EXISTS `st_categories` (
  `ID` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `ID_user` BIGINT(20) UNSIGNED NOT NULL,
  `name` VARCHAR(50) NOT NULL DEFAULT '',
  `slug` VARCHAR(50) NOT NULL DEFAULT '',
  `taxonomy` VARCHAR(100) NOT NULL DEFAULT '',
  `description` TEXT(300) DEFAULT '',
  `count_used` BIGINT(20),
  PRIMARY KEY (`ID`),
  FOREIGN KEY (`ID_user`) REFERENCES `wp_users`(ID) ON DELETE CASCADE ON UPDATE CASCADE
);