CREATE TABLE IF NOT EXISTS `st_ratings` (
  `ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ID_user` BIGINT(20) NOT NULL,
  `ID_post` BIGINT(20) NOT NULL,
  `ID_rating_parent` BIGINT(20),
  `name_author` VARCHAR(50) NOT NULL,
  `star` BIGINT(1) NOT NULL,
  `title` VARCHAR(50) NOT NULL,
  `description` TEXT(300),
  `likes` BIGINT(20),
  `deslikes` BIGINT(20),
  `is_response` BOOLEAN NOT NULL,

  PRIMARY KEY (`ID`),
  FOREIGN KEY (`ID_user`) REFERENCES `st_users`(ID) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (`ID_post`) REFERENCES `wp_posts`(ID) ON DELETE CASCADE ON UPDATE CASCADE,
);